#include "../header/ExibeMenu.h"

using namespace std;

void exibeMenu(){
	system("clear");
	system("clear");

	cout << COR_CIANO;
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "                                                          ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "                    ╔════════════════╗                    ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ╔════════════════╣      MENU      ╠════════════════╗   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║                ╚════════════════╝                ║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║                                                  ║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║";
	cout << COR_VERMELHO;
	cout <<       "      TECLA              FUNÇÃO                   ";
	cout << COR_CIANO <<                                         "║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║";
	cout << COR_AZUL;
	cout <<       "        0            Camera Traseira              ";
	cout << COR_CIANO <<                                         "║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║";
	cout << COR_PRETO;
	cout <<       "        1            Camera Lateral Direita       ";
	cout << COR_CIANO <<                                         "║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║";
	cout << COR_AZUL;
	cout <<       "        2            Camera Diagonal Direita      ";
	cout << COR_CIANO <<                                         "║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║";
	cout << COR_PRETO;
	cout <<       "        3            Camera Frontal               ";
	cout << COR_CIANO <<                                         "║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║";
	cout << COR_AZUL;
	cout <<       "        4            Camera Diagonal Esquerda     ";
	cout << COR_CIANO <<                                         "║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║";
	cout << COR_PRETO;
	cout <<       "        5            Camera Lateral Esquerda      ";
	cout << COR_CIANO <<                                         "║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║";
	cout << COR_AZUL;
	cout <<       "        6            Camera Superior              ";
	cout << COR_CIANO <<                                         "║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║                                                  ║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║";
	cout << COR_PRETO;
	cout <<       "        +            Aumenta Zoom                 ";
	cout << COR_CIANO <<                                         "║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║";
	cout << COR_AZUL;
	cout <<       "        -            Diminui Zoom                 ";
	cout << COR_CIANO <<                                         "║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ║                                                  ║   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "   ╚══════════════════════════════════════════════════╝   ";
	cout << FUNDO_NORMAL << "\n  " << FUNDO_BRANCO;
	cout << "                                                          ";
	cout << COR_NORMAL;
	cout << FUNDO_NORMAL;
	cout << "\n\n";

}